name: Test GitHub Actions
# on: [push]
on:
  push:
    branches: [cicd/*]

jobs:
  Explore-GitHub-Actions:
    runs-on: [self-hosted, some-label] #ubuntu-18.04
    # defaults:
    #   run:
    #     working-directory: umap-web

    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - name: Check out repository code
        uses: actions/checkout@v3

      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - name: List files in umap-web
        working-directory: umap-web
        run: |
            ls .

      - name: List files after using working-directory
        run: |
            ls .

      - name: Setup node  ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: 'umap-web/package-lock.json'
    
      - name: npm ci
        working-directory: umap-web
        run: npm ci

      - name: npm run build
        working-directory: umap-web
        run: npm run build --if-present

      - run: echo "ğŸ This job's status is ${{ job.status }}."